# File created by ansible 

version: '2'
services:

  app:
    image: cscfi/rems:v2.37
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://db:5432/rems?user=rems&password=remspassword
      AUTHENTICATION: :oidc
      OIDC_METADATA_URL: https://test.cilogon.aaf.edu.au/.well-known/openid-configuration
      OIDC_CLIENT_ID: cilogon:/client_id/9196201816087da27d1d005811eba36
      OIDC_CLIENT_SECRET: 1Q66sUAt91eK-_6iNXdUrZtB77lALtiK-O9gj6KRM5pW73rLxlC062DVc36sY0t5PtoDcAtOxZs4i0HXaA3wQw
      PUBLIC_URL: http://localhost:3000/
    mem_reservation: 200m
    mem_limit: 2000m
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./config.edn:/rems/config/config.edn
      - ./extra-styles.css:/rems/ldaca-theme/extra-styles.css
      - ./extra-pages:/rems/extra-pages
      - ./translations:/rems/resources/translations
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rems
      POSTGRES_PASSWORD: remspassword
    mem_reservation: 30m
    mem_limit: 150m
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
