# File created by ansible 

version: '2'
services:

  app:
    image: cscfi/rems:v2.29
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://db:5432/rems?user=rems&password=remspassword
      AUTHENTICATION: :oidc
      OIDC_METADATA_URL: https://test.cilogon.org/.well-known/openid-configuration
      OIDC_CLIENT_ID: cilogon:/client_id/164ab138a8a4e8be028c57778653241f
      OIDC_CLIENT_SECRET: pHr7BlNYMt2mxaeepz84cJHbf4yEK51OifGzaCfkmrK_EF7pW9oOntdvlst4oHQMx-EjN1ZUD6feoPJbYh2JVQ
      PUBLIC_URL: http://localhost:3000/
    mem_reservation: 200m
    mem_limit: 2000m
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./config.edn:/rems/config/config.edn
      - ./extra-styles.css:/rems/ldaca-theme/extra-styles.css
      - ./extra-pages:/rems/extra-pages
      - ./translations:/rems/resources/translations
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rems
      POSTGRES_PASSWORD: remspassword
    mem_reservation: 30m
    mem_limit: 150m
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"